language: c
sudo: required

matrix:
  include:
    - compiler: "gcc"
      os: linux
      env:
        - BUILD_TYPE=m1k_make
    - compiler: "gcc"
      os: linux
      env:
        - BUILD_TYPE=cppcheck
    - compiler: "gcc"
      os: linux
      env:
        - BUILD_TYPE=astyle

addons:
  artifacts: true

script:
  - ./ci/travis/run_build

notifications:
  email:
    on_success: change
    on_failure: always
