#!/bin/sh -xe

handle_default() {
	sudo apt-get -qq update
	# libstdc++-arm-none-eabi-newlib is required mostly for build
	# there is no C++ code in this repo
	sudo apt-get install -y gcc-arm-none-eabi \
		libstdc++-arm-none-eabi-newlib
}

BUILD_TYPE=${BUILD_TYPE:-default}

handle_${BUILD_TYPE}
